name: Notify on Build Failure

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Test
        run: npm test

      - name: Notify Slack on Failure
        if: failure()
        uses:  rtCamp/action-slack-notify@v2
        with:
          env: SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "Build Failed! Check the logs."
