name: Hello World

on:
  push:
  workflow_dispatch:
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Print message
          run: echo "Hello from Github Actions!"

        - name: show date
          run: date

        - name: Show working directory
          run: pwd
    
